# Q1. Create a null vector of size 10 but the fifth value which is 1

In [2]:
import numpy as np
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Q2. Create a vector with values ranging from 10 to 49

In [4]:
array1 = np.arange(10,50)
print(array1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Q3. Create a 3x3 matrix with values ranging from 0 to 8

In [5]:
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Q4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [7]:
given_array = np.array([1,2,0,0,4,0])
print(given_array.nonzero())

(array([0, 1, 4], dtype=int64),)


# Q5. Create a 10x10 array with random values and find the minimum and maximum values

In [11]:
array2 = np.random.randn(10,10)
minimum = array2.min()
maximum = array2.max()
print(array2)
print('Minimum Value : %s \nMaximum Value : %s' %(minimum,maximum))

[[ 1.61119602 -1.96769219 -1.1194031  -2.10937094  0.90765829  1.00829388
   0.25299111  1.92651301 -0.19559188 -0.44219882]
 [ 0.20444406  0.33776837  1.05862053  0.1096202  -0.00815501  0.53687246
  -0.02962341  1.43263245  0.86039023 -0.51092094]
 [ 0.80761872  1.68897548 -0.34144476 -0.64843898  0.32042471  1.9774481
  -1.10560181 -0.47015328  0.74736431  1.07271944]
 [ 1.11175538 -1.49657626  1.22822042 -0.44424586 -1.98935226 -0.65749571
   0.35525733  0.61863919  1.94638944 -1.01438735]
 [ 0.42357684  1.65332187  0.82622508 -0.74830949  0.48160659 -0.41848153
  -0.59006475 -0.47944997  1.59018439  0.44227008]
 [ 0.59121936 -1.32084619 -1.15464647  0.68339436  1.81301315  0.63314947
  -1.27310674 -0.55197452  0.11563528 -1.87087748]
 [ 0.22930014 -0.11787355 -0.38466532 -0.86808751 -0.43391243 -0.00469104
  -0.37509143 -0.98845089  0.17777044  0.52853642]
 [ 1.50840022  1.03198666  0.28392437 -0.35729373 -0.06782942  0.37236919
  -0.2355152   1.55817535 -0.58344666  1.0460987 ]
 

# Q6. Create a random vector of size 30 and find the mean value

In [12]:
array3 = np.random.random(30)
mean_value = array3.mean()
print('Mean Value :',mean_value)

Mean Value : 0.5379354604606664
